# Generated by Django 5.1.3 on 2026-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_alter_event_created_at_alter_photo_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
