# Generated by Django 5.1.7 on 2026-01-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_event_created_at_alter_photo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images/', width_field='width'),
        ),
    ]
