# Generated by Django 5.1.3 on 2026-01-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_alter_profile_created_at"),
        ("gallery", "0009_photo_height_photo_width_alter_photo_image"),
    ]

    operations = []
